import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "../../constants/navigation.constant";
import {
  SUPER_ADMIN,
  ADMIN,
  SUB_ADMIN,
  EXECUTIVE,
} from "../../constants/roles.constant";

const superAdminNavigationConfig = [
  {
    key: "pages",
    path: "",
    title: "PAGES",
    translateKey: "nav.pages",
    icon: "pages",
    type: "title",
    authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN, EXECUTIVE],
    subMenu: [
      {
        key: "dashboard",
        path: `/dashboard`,
        title: "Dashboard",
        translateKey: "nav.dashboard",
        icon: "dashboard",
        type: "item",
        authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN, EXECUTIVE],
        subMenu: [],
      },
      {
        key: "user",
        path: `/company/user`,
        title: "User",
        translateKey: "nav.user",
        icon: "user",
        type: "item",
        authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
        subMenu: [],
      },

      {
        key: "task",
        path: "",
        title: "Task",
        translateKey: "nav.task",
        icon: "task",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
        subMenu: [
          {
            key: "task.list",
            path: `/task/list`,
            title: "Task List",
            translateKey: "nav.task.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
        ],
      },
      {
        key: "customer",
        path: "",
        title: "Customer",
        translateKey: "nav.customer",
        icon: "customer",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN, "executive"],
        subMenu: [
          {
            key: "customer.dashboard",
            path: `/customer/dashboard`,
            title: "Dashboard",
            translateKey: "nav.customer.dashboard",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN, "executive"],
            subMenu: [],
          },
          {
            key: "customer.list",
            path: `/customer/list`,
            title: "Customer List",
            translateKey: "nav.customer.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
          {
            key: "customer.new",
            path: `/customer/new`,
            title: "New Customer",
            translateKey: "nav.customer.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "product",
        path: "",
        title: "Product",
        translateKey: "nav.dashboard",
        icon: "product",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
        subMenu: [
          {
            key: "product.list",
            path: `/product/list`,
            title: "Product List",
            translateKey: "nav.product.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
          {
            key: "product.new",
            path: `/product/new`,
            title: "New Product",
            translateKey: "nav.product.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
          {
            key: "product.setting",
            path: `/product/settings`,
            title: "Settings",
            translateKey: "nav.product.setting",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
          {
            key: "product.dashboard",
            path: `/product/dashboard`,
            title: "Dashboard",
            translateKey: "nav.product.dashboard",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "stock",
        path: `/master/stock`,
        title: "Stock",
        translateKey: "nav.stock",
        icon: "stock",
        type: "item",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [],
      },
      {
        key: "purchase.order",
        path: "",
        title: "Order Management",
        translateKey: "nav.purchase.order",
        icon: "orders",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [
          {
            key: "purchase.order.list",
            path: `/po/list`,
            title: "Order List",
            translateKey: "nav.purchase.order.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          {
            key: "purchase.order.new",
            path: `/po/new`,
            title: "New Order",
            translateKey: "nav.purchase.order.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          {
            key: "purchase.settings",
            path: `/po/setting`,
            title: "Settings",
            translateKey: "nav.purchase.settings",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "invoice",
        path: "",
        title: "Invoices",
        translateKey: "nav.invoice",
        icon: "invoice",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
        subMenu: [
          {
            key: "foreign.new",
            path: `/dispatch/foreign/new`,
            title: "Foreign Invoice",
            translateKey: "nav.foreign.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
          {
            key: "domestic.new",
            path: `/dispatch/domestic/new`,
            title: "Domestic Invoice",
            translateKey: "nav.domestic.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
          {
            key: "pattern.new",
            path: `/dispatch/pattern/new`,
            title: "Pattern Invoice",
            translateKey: "nav.pattern.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
          {
            key: "invoice.setting",
            path: `/dispatch/invoice/setting`,
            title: "Settings",
            translateKey: "nav.foreign.setting",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
          {
            key: "invoice.list",
            path: `/dispatch-list`,
            title: "Invoice List",
            translateKey: "nav.invoice.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
        ],
      },

      {
        key: "master.planner",
        path: `/master/product/planner`,
        title: "Master PP",
        translateKey: "nav.master.planner",
        icon: "master",
        type: "item",
        authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
        subMenu: [],
      },

      {
        key: "quality.control",
        path: "",
        title: "Quality Control",
        translateKey: "nav.quality",
        icon: "quality",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
        subMenu: [
          {
            key: "quality.form.new",
            path: `/quality/new`,
            title: "Quality Form",
            translateKey: "nav.quality.form.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, EXECUTIVE],
            subMenu: [],
          },
        ],
      },

      {
        key: "workers",
        path: `/workers`,
        title: "HR",
        translateKey: "nav.workers",
        icon: "worker",
        type: "item",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [],
      },
      {
        key: "purchase.order",
        path: "",
        title: "Purchase Order",
        translateKey: "nav.purchase.order",
        icon: "purchase",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [
          {
            key: "purchase.order.list",
            path: `/purchaseOrder/list`,
            title: "PO List",
            translateKey: "nav.purchase.order.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          {
            key: "purchase.order.new",
            path: `/purchaseOrder/new`,
            title: "New PO",
            translateKey: "nav.purchase.order.new",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          {
            key: "purchase.order.inward",
            path: `/purchaseOrder/inward/list`,
            title: "Inward List",
            translateKey: "nav.purchase.order.inward",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "sales",
        path: "",
        title: "Sales",
        translateKey: "nav.sales",
        icon: "purchase",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [
          {
            key: "enquiry.list",
            path: `/enquiry/List`,
            title: "Enquiry List",
            translateKey: "nav.enquiry.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          // {
          //   key: 'enquiry.new',
          //   path: `/enquiry/new`,
          //   title: 'New Enquiry',
          //   translateKey: 'nav.enquiry.new',
          //   type: 'item',
          //   authority: [SUPER_ADMIN, ADMIN],
          //   subMenu: []
          // },
          {
            key: "quotation.list",
            path: `/quotation`,
            title: "Quotation",
            translateKey: "nav.quotation.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "machines",
        path: "",
        title: "Machines",
        translateKey: "nav.machine",
        icon: "purchase",
        type: "collapse",
        authority: [SUPER_ADMIN, ADMIN],
        subMenu: [
          {
            key: "machine.list",
            path: `/machine/List`,
            title: "Machines",
            translateKey: "nav.machine.list",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
          {
            key: "machine.breakdown",
            path: `/machine/breakdown`,
            title: "Machine Breakdown",
            translateKey: "nav.machine.breakdown",

            type: "item",
            authority: [SUPER_ADMIN, ADMIN],
            subMenu: [],
          },
        ],
      },
      {
        key: "instruments",
        path: "",
        title: "INSTRUMENTS",
        translateKey: "nav.instruments.instruments",
        icon: "instrument",
        type: "collapse",
        authority: [],
        subMenu: [
          {
            key: "dashboard",
            path: `/instrument/dashboard`,
            title: "Dashboard",
            translateKey: "nav.dashboard",
            icon: "",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN, EXECUTIVE],
            subMenu: [],
          },
          {
            key: "instrument",
            path: `/instrument/list`,
            title: "Instrument",
            translateKey: "nav.instrument",
            icon: "",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
          {
            key: "calibration",
            path: `/instrument/calibration`,
            title: "Calibration",
            translateKey: "nav.calibration",
            icon: "",
            type: "item",
            authority: [SUPER_ADMIN, ADMIN, SUB_ADMIN],
            subMenu: [],
          },
        ],
      },
    ],
  },
];

export default superAdminNavigationConfig;
